# Gitlab education - Gitlab Community Edition
# Persistent volume for gitlab data store.

version: '3.4'
services:

  cicd-gitlab:
    image: gitlab/gitlab-ce:latest
    volumes:
      - gitlab-log:/var/log/gitlab
      - gitlab-opt:/var/opt/gitlab
    secrets:
       - source: gitlab.rb
         target: /etc/gitlab/gitlab.rb
    hostname: cicd
    container_name: cicd
    restart: always
    networks:
       EDU_GITLAB_Net:
         ipv4_address: 101.101.101.2
    ports:
      - "0.0.0.0:80:80/tcp"
      - "0.0.0.0:443:443/tcp"
      - "0.0.0.0:4567:4567/tcp"

networks:
  EDU_GITLAB_Net:
    driver: bridge
    ipam:
      config:
        - subnet: 101.101.101.0/24

secrets:
  gitlab.rb:
    file: ./gitlab/conf/gitlab.rb

volumes:
  gitlab-log:
  gitlab-opt:
